/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    ArticleList: typeof import('./src/views/home/views/article-list.vue')['default']
    Dashboard: typeof import('./src/views/dashboard/index.vue')['default']
    Home: typeof import('./src/views/home/index.vue')['default']
    LifeTrends: typeof import('./src/views/home/views/life-trends.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NSpace: typeof import('naive-ui')['NSpace']
    PageLayout: typeof import('./src/components/layout/page-layout/index.vue')['default']
    Readarticle: typeof import('./src/views/readarticle/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskList: typeof import('./src/views/home/views/task-list.vue')['default']
    WebNav: typeof import('./src/views/home/views/web-nav.vue')['default']
  }
}
